---
- name: Local Deploy Git Hook Rules
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: 5001
  rules:
    - name: run tests 1
      condition: event.payload.repo == "{{repo}}"
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
    - name: print output
      condition: event.output is defined
      action:
        print_event:
          var_root: output
...
